{% set name = "anaconda-cloud-cli" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_cli-{{ version }}.tar.gz
  sha256: 62f897a83641340599c908874b0a31903ff79881d693ddbaade2905f526ac231

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8
    - anaconda-cli-base
    - anaconda-cloud-auth

test:
  imports:
    - anaconda_cloud_cli
  commands:
    - python -c "from anaconda_cloud_cli import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: The Anaconda Cloud CLI
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
