{% set name = "anaconda-cloud-cli" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cloud_cli-{{ version }}.tar.gz
  sha256: b72b3008ea3b57f11dbe5535db9c016f594ac378fb15dea3b52874ad279fcd62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8
    - anaconda-cli-base >=0.2,<0.3
    - anaconda-cloud-auth >=0.3,<0.6
    - anaconda-client >=1.12.2,<1.13

test:
  imports:
    - anaconda_cloud_cli
    - binstar_client
  commands:
    - python -c "from anaconda_cloud_cli import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: The Anaconda Cloud CLI
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
